name: Trigger auto sync
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Run Katalon Tests
        run: |
          # Set the project path
          PROJECT_PATH="${{ github.workspace }}/katalon-sample-api-tests/web-service-tests.prj"
          
          # Run the Katalon command
          katalonc -noSplash \
            -runMode=console \
            -projectPath="$PROJECT_PATH" \
            -retry=0 \
            -testSuitePath="Test Suites/web-service-tests - All Test Cases" \
            -browserType="Web Service" \
            -executionProfile="default" \
            -apiKey="${{ secrets.PROJECT }}" \
            --config \
            -proxy.auth.option=NO_PROXY \
            -proxy.system.option=NO_PROXY \
            -proxy.system.applyToDesiredCapabilities=true \
            -webui.autoUpdateDrivers=true
