name: Trigger auto sync
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2.1
        with:
          version: '9.7.2'
          #projectPath: '/home/runner/work/katalon-sample-api-tests'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=1 -browserType="Web Service" -executionProfile="default" -statusDelay=15 -testSuitePath="Test Suites/web-service-tests - All Test Cases" -apiKey="${{ secrets.PROJECT }}" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
